# config.yaml

defaults:
  epoch: 1000
  patience: 1000
  num_workers: 2
  lr: 1e-4
  lr_sched: 'cosine'
  min_lr: 1e-6
  warmup_lr: 1e-6
  warmup_epochs: 0

# batch_size is the global batch size; DDP divides it across processes.
matching: # 4gpus
  batch_size: 1024

spt: # 4gpus
  batch_size: 128

rxn:
  batch_size: 16
